### PR TITLE
added some animation

### PR DESCRIPTION
**Pull request by shaner0892**
Be in main
Execute git fetch --all
Execute git checkout hrs-part3
Execute code .

I added two animations: snacks, snacks, snacks should slide back and forth as well as the pantry list. They slide at different speeds. I will probably change these later but since they're working I left them for now!

### CODE REVIEW

**Comment by gregoryhaney** [comment]
I reviewed. 
Your animation looks great; however, the majority of the keyframe code I added to the **main.css** file is missing. You may need to grab the most current main branch and pull it down, merge it with your branch, and then push it back to GitHub.

**Comment by gregoryhaney** [comment]
Also, Steve's pic isn't showing up, which was added to the **index.html** file.

**Comment by shaner0892** [comment]
I merged the branch again, so it should be working now!

**Review by gregoryhaney — APPROVED** [review]
Good to go!

**Pull request merged**
